// services/api-gateway/src/middleware/errorHandler.ts

import { Request, Response, NextFunction } from "express";
import logger from "../utils/logger";

export default function errorHandler(
  err: Error,
  req: Request,
  res: Response,
  next: NextFunction
): void {
  // Get the request ID generated by Pino
  const requestId = (req as any).id;

  // Log the error with structured format
  logger.error({
    msg: `Unhandled error: ${err.message}`,
    error: err.message,
    stack: err.stack,
    path: req.path,
    requestId: requestId,
  });

  res.status(500).json({
    error: "Internal Server Error",
    correlationId: requestId,
  });
}
